export const LOAN_INDEXCHANGED = 'MainGrid/LOAN/INDEXCHANGED';
export const LOAN_CLEARSELECTED = 'MainGrid/LOAN/CLEARSELECTED';

export const BORROWER_INDEXCHANGED = 'MainGrid/BORROWER/INDEXCHANGED';
export const BORROWER_CLEARSELECTED = 'MainGrid/BORROWER/CLEARSELECTED';

export const INFO_INDEXCHANGED = 'MainGrid/INFO/INDEXCHANGED';
export const INFO_CLEARSELECTED = 'MainGrid/INFO/CLEARSELECTED';
export const INFO_LOANMODIFIED = 'MainGrid/INFO/LOANMODIFIED';
export const INFO_LOANADDED = 'MainGrid/INFO/LOANADDED';

export const LOADED_LOANS = 'Loading/LOANS';
export const LOADED_BORROWERS = 'Loading/BORROWERS';